import { Template } from './types';

export const generateId = () => Math.random().toString(36).substring(2, 9);

export const FONTS = [
  { name: 'System Default', value: 'system-ui, sans-serif' },
  { name: 'Noto Sans SC', value: '"Noto Sans SC", sans-serif' },
  { name: 'Noto Serif SC', value: '"Noto Serif SC", serif' },
  { name: 'ZCOOL KuaiLe', value: '"ZCOOL KuaiLe", cursive' },
  { name: 'Ma Shan Zheng', value: '"Ma Shan Zheng", cursive' },
  { name: 'Playfair Display', value: '"Playfair Display", serif' },
  { name: 'Inter', value: '"Inter", sans-serif' },
];

export const TEMPLATES: Template[] = [
  {
    id: 'xhs-1',
    name: '极简语录 (XHS)',
    category: 'xhs',
    thumbnail: 'https://picsum.photos/seed/xhs1/200/266',
    state: {
      width: 1080,
      height: 1440,
      background: { type: 'color', value: '#FDFBF7' },
      elements: [
        {
          id: generateId(),
          type: 'text',
          text: '“',
          x: 100,
          y: 200,
          width: 200,
          height: 200,
          rotation: 0,
          opacity: 0.2,
          zIndex: 1,
          fontSize: 300,
          fontFamily: '"Noto Serif SC", serif',
          fontWeight: '700',
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 0,
        },
        {
          id: generateId(),
          type: 'text',
          text: '生活不是等待暴风雨过去，\n而是学会在雨中跳舞。',
          x: 150,
          y: 500,
          width: 780,
          height: 400,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 64,
          fontFamily: '"Noto Serif SC", serif',
          fontWeight: '400',
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.6,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'text',
          text: '- 每日灵感 -',
          x: 150,
          y: 1100,
          width: 780,
          height: 100,
          rotation: 0,
          opacity: 0.6,
          zIndex: 3,
          fontSize: 36,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '300',
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 4,
        }
      ]
    }
  },
  {
    id: 'xhs-2',
    name: '好物分享 (XHS)',
    category: 'xhs',
    thumbnail: 'https://picsum.photos/seed/xhs2/200/266',
    state: {
      width: 1080,
      height: 1440,
      background: { type: 'color', value: '#FFE5E5' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 80,
          y: 80,
          width: 920,
          height: 1280,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          backgroundColor: '#FFFFFF',
          borderRadius: 40,
        },
        {
          id: generateId(),
          type: 'image',
          src: 'https://picsum.photos/seed/product/800/800',
          x: 140,
          y: 140,
          width: 800,
          height: 800,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          objectFit: 'cover',
          borderRadius: 20,
        },
        {
          id: generateId(),
          type: 'text',
          text: '年度爱用物大公开',
          x: 140,
          y: 1000,
          width: 800,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 80,
          fontFamily: '"ZCOOL KuaiLe", cursive',
          fontWeight: '400',
          color: '#FF4D4F',
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'text',
          text: '提升幸福感的神仙好物，不允许你不知道！',
          x: 140,
          y: 1150,
          width: 800,
          height: 80,
          rotation: 0,
          opacity: 0.8,
          zIndex: 4,
          fontSize: 36,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '400',
          color: '#666666',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 1,
        }
      ]
    }
  },
  {
    id: 'xhs-3',
    name: 'Vlog封面 (XHS)',
    category: 'xhs',
    thumbnail: 'https://picsum.photos/seed/xhs3/200/266',
    state: {
      width: 1080,
      height: 1440,
      background: { type: 'image', value: 'https://picsum.photos/seed/vlog/1080/1440' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 1080,
          height: 1440,
          rotation: 0,
          opacity: 0.3,
          zIndex: 1,
          backgroundColor: '#000000',
        },
        {
          id: generateId(),
          type: 'text',
          text: 'MY VLOG',
          x: 100,
          y: 500,
          width: 880,
          height: 200,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 160,
          fontFamily: '"Playfair Display", serif',
          fontWeight: '900',
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1,
          letterSpacing: 10,
          textShadow: '0px 4px 20px rgba(0,0,0,0.5)'
        },
        {
          id: generateId(),
          type: 'text',
          text: '周末碎片 / 治愈日常',
          x: 100,
          y: 750,
          width: 880,
          height: 100,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 48,
          fontFamily: '"Noto Serif SC", serif',
          fontWeight: '400',
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1,
          letterSpacing: 8,
        }
      ]
    }
  },
  {
    id: 'xhs-4',
    name: '美食教程 (XHS)',
    category: 'xhs',
    thumbnail: 'https://picsum.photos/seed/xhs4/200/266',
    state: {
      width: 1080,
      height: 1440,
      background: { type: 'color', value: '#FFF8E7' },
      elements: [
        {
          id: generateId(),
          type: 'image',
          src: 'https://picsum.photos/seed/food/1080/900',
          x: 0,
          y: 0,
          width: 1080,
          height: 900,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          objectFit: 'cover',
        },
        {
          id: generateId(),
          type: 'text',
          text: '零失败教程',
          x: 80,
          y: 950,
          width: 300,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 36,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '700',
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 80,
          y: 950,
          width: 240,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          backgroundColor: '#FF8C00',
          borderRadius: 30,
        },
        {
          id: generateId(),
          type: 'text',
          text: '爆款芝士热狗棒',
          x: 80,
          y: 1050,
          width: 920,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 96,
          fontFamily: '"Ma Shan Zheng", cursive',
          fontWeight: '400',
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.2,
          letterSpacing: 4,
        },
        {
          id: generateId(),
          type: 'text',
          text: '外酥里嫩，一口爆浆！有手就会做~',
          x: 80,
          y: 1200,
          width: 920,
          height: 80,
          rotation: 0,
          opacity: 0.8,
          zIndex: 4,
          fontSize: 40,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '400',
          color: '#666666',
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 1,
        }
      ]
    }
  },
  {
    id: 'xhs-5',
    name: 'OOTD穿搭 (XHS)',
    category: 'xhs',
    thumbnail: 'https://picsum.photos/seed/xhs5/200/266',
    state: {
      width: 1080,
      height: 1440,
      background: { type: 'image', value: 'https://picsum.photos/seed/ootd/1080/1440' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 60,
          y: 60,
          width: 960,
          height: 1320,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          backgroundColor: 'transparent',
          borderRadius: 0,
        },
        {
          id: generateId(),
          type: 'text',
          text: 'OOTD',
          x: 100,
          y: 100,
          width: 400,
          height: 150,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 120,
          fontFamily: '"Inter", sans-serif',
          fontWeight: '900',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 5,
          textShadow: '2px 2px 10px rgba(0,0,0,0.3)'
        },
        {
          id: generateId(),
          type: 'text',
          text: 'Vol. 024',
          x: 100,
          y: 250,
          width: 300,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 40,
          fontFamily: '"Inter", sans-serif',
          fontWeight: '400',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 2,
          textShadow: '1px 1px 5px rgba(0,0,0,0.3)'
        },
        {
          id: generateId(),
          type: 'text',
          text: '早秋氛围感穿搭\n慵懒又高级',
          x: 100,
          y: 1150,
          width: 880,
          height: 150,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          fontSize: 64,
          fontFamily: '"Noto Serif SC", serif',
          fontWeight: '700',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1.4,
          letterSpacing: 2,
          textShadow: '2px 2px 10px rgba(0,0,0,0.5)'
        }
      ]
    }
  },
  {
    id: 'wechat-1',
    name: '科技资讯 (WeChat)',
    category: 'wechat',
    thumbnail: 'https://picsum.photos/seed/wechat1/200/85',
    state: {
      width: 900,
      height: 383,
      background: { type: 'gradient', value: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)' },
      elements: [
        {
          id: generateId(),
          type: 'text',
          text: 'TECH NEWS',
          x: 50,
          y: 50,
          width: 300,
          height: 40,
          rotation: 0,
          opacity: 0.8,
          zIndex: 1,
          fontSize: 24,
          fontFamily: '"Inter", sans-serif',
          fontWeight: '700',
          color: '#00E5FF',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 4,
        },
        {
          id: generateId(),
          type: 'text',
          text: 'AI大模型迎来史诗级更新！',
          x: 50,
          y: 120,
          width: 800,
          height: 100,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 64,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '900',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'text',
          text: '深度解析背后的技术突破与行业影响',
          x: 50,
          y: 240,
          width: 800,
          height: 50,
          rotation: 0,
          opacity: 0.7,
          zIndex: 3,
          fontSize: 32,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '400',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 1,
        }
      ]
    }
  },
  {
    id: 'wechat-2',
    name: '生活方式 (WeChat)',
    category: 'wechat',
    thumbnail: 'https://picsum.photos/seed/wechat2/200/85',
    state: {
      width: 900,
      height: 383,
      background: { type: 'image', value: 'https://picsum.photos/seed/lifestyle/900/383' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 900,
          height: 383,
          rotation: 0,
          opacity: 0.4,
          zIndex: 1,
          backgroundColor: '#000000',
        },
        {
          id: generateId(),
          type: 'text',
          text: 'LIFESTYLE',
          x: 0,
          y: 80,
          width: 900,
          height: 40,
          rotation: 0,
          opacity: 0.9,
          zIndex: 2,
          fontSize: 24,
          fontFamily: '"Playfair Display", serif',
          fontWeight: '400',
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1,
          letterSpacing: 8,
        },
        {
          id: generateId(),
          type: 'text',
          text: '如何度过一个高质量的周末？',
          x: 50,
          y: 160,
          width: 800,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 56,
          fontFamily: '"Noto Serif SC", serif',
          fontWeight: '700',
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 4,
        },
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 400,
          y: 280,
          width: 100,
          height: 2,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          backgroundColor: '#FFFFFF',
        }
      ]
    }
  },
  {
    id: 'wechat-3',
    name: '极简排版 (WeChat)',
    category: 'wechat',
    thumbnail: 'https://picsum.photos/seed/wechat3/200/85',
    state: {
      width: 900,
      height: 383,
      background: { type: 'color', value: '#F4F4F4' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 40,
          y: 40,
          width: 820,
          height: 303,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          backgroundColor: '#FFFFFF',
          borderRadius: 16,
        },
        {
          id: generateId(),
          type: 'text',
          text: '01',
          x: 80,
          y: 80,
          width: 100,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 64,
          fontFamily: '"Inter", sans-serif',
          fontWeight: '900',
          color: '#E0E0E0',
          textAlign: 'left',
          lineHeight: 1,
          letterSpacing: 0,
        },
        {
          id: generateId(),
          type: 'text',
          text: '极简主义指南',
          x: 80,
          y: 180,
          width: 740,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 56,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '700',
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'text',
          text: '少即是多，给生活做减法',
          x: 80,
          y: 280,
          width: 740,
          height: 40,
          rotation: 0,
          opacity: 0.6,
          zIndex: 4,
          fontSize: 28,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '400',
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 1,
        }
      ]
    }
  },
  {
    id: 'wechat-4',
    name: '重磅发布 (WeChat)',
    category: 'wechat',
    thumbnail: 'https://picsum.photos/seed/wechat4/200/85',
    state: {
      width: 900,
      height: 383,
      background: { type: 'color', value: '#D32F2F' },
      elements: [
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'circle',
          x: 600,
          y: -100,
          width: 500,
          height: 500,
          rotation: 0,
          opacity: 0.1,
          zIndex: 1,
          backgroundColor: '#FFFFFF',
        },
        {
          id: generateId(),
          type: 'text',
          text: '重磅发布',
          x: 80,
          y: 80,
          width: 200,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 32,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '900',
          color: '#D32F2F',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 80,
          y: 80,
          width: 200,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          backgroundColor: '#FFFFFF',
          borderRadius: 4,
        },
        {
          id: generateId(),
          type: 'text',
          text: '2026年度报告出炉！',
          x: 80,
          y: 180,
          width: 740,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          fontSize: 64,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '900',
          color: '#FFFFFF',
          textAlign: 'left',
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'text',
          text: '一文看懂行业未来趋势',
          x: 80,
          y: 280,
          width: 740,
          height: 40,
          rotation: 0,
          opacity: 0.9,
          zIndex: 4,
          fontSize: 32,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '400',
          color: '#FFCDD2',
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 1,
        }
      ]
    }
  },
  {
    id: 'wechat-5',
    name: '大字报 (WeChat)',
    category: 'wechat',
    thumbnail: 'https://picsum.photos/seed/wechat5/200/85',
    state: {
      width: 900,
      height: 383,
      background: { type: 'color', value: '#FFEB3B' },
      elements: [
        {
          id: generateId(),
          type: 'text',
          text: '搞钱必看',
          x: 50,
          y: 60,
          width: 800,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          fontSize: 100,
          fontFamily: '"ZCOOL KuaiLe", cursive',
          fontWeight: '400',
          color: '#000000',
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 8,
        },
        {
          id: generateId(),
          type: 'text',
          text: '普通人如何抓住下一个风口？',
          x: 50,
          y: 220,
          width: 800,
          height: 80,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 48,
          fontFamily: '"Noto Sans SC", sans-serif',
          fontWeight: '900',
          color: '#000000',
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: generateId(),
          type: 'shape',
          shapeType: 'rectangle',
          x: 50,
          y: 220,
          width: 800,
          height: 80,
          rotation: -2,
          opacity: 1,
          zIndex: 1,
          backgroundColor: '#FFFFFF',
          borderRadius: 8,
        }
      ]
    }
  }
];
